export function getBranchName(projectId: string) {
  return `nexus/project-${projectId.slice(0,8)}`
}
export function getCommitMessage(status: string) {
  return `feat(nexus): ${status} - auto generated by NEXUS V8`
}
